### ISSUE TITLE
LevelKu functions causes errors

### ISSUE THREAD

**Issue by ghost** [nanite/KubeUtils#3]
When I try to use LevelKu functions, I get errors about their absence

! [12:09:55] [ERR] #25: Error occurred while handling event 'BlockEvents.broken': TypeError: Cannot find function getRandomLocation in object ServerLevel[Новый мир]. (server_scripts:block/mainBlock.js#25)

**Comment by MichaelHillcox** [comment]
Please provide the full logs and the code that is causing issues

**Comment by 8sixik** [comment]
[ERROR.zip](https://github.com/ErrorMikey/KubeUtils/files/11264389/ERROR.zip)

**Comment by MichaelHillcox** [comment]
Your code does not show you using KubeUtils just KubeJS
