### ISSUE TITLE
[Issue] Modrinth wiki link points to wrong page

### ISSUE THREAD

**Issue by Aiz0** [nanite/KubeUtils#6]
### Minecraft Version

N/A

### Modloader

N/A

### Mod version

N/A

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

N/A

### Steps to reproduce the issue

1. go to https://modrinth.com/mod/kube-utils
2. click on visit wiki
3. you end up at https://errormikey.github.io/KubeUtils/ instead of https://nanite.github.io/KubeUtils/

### Description of the issue you are having

Modrinth wiki link points to a page that no longer exists.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Whoops! Missed this on... Thanks for the report. I've fixed this <3
